### ISSUE TITLE
miss /data/datasets directory

### ISSUE THREAD

**Issue by OdinLin** [SummaLabs/DLS#1]
Hi, when i follow the [How to build and run], I've got the error "Exception: Cant find directory with datasets [/root/PycharmProjects/DLS/dataset-import-test/../data/datasets]"  , when I mkdir in data/datasets, It work well, Is It the right way I do? Thank you 

full log:
Traceback (most recent call last):
  File "/root/PycharmProjects/DLS/run-app.py", line 2, in <module>
    from app.backend import app_flask, socketio
  File "/root/PycharmProjects/DLS/app/backend/__init__.py", line 47, in <module>
    from app.backend import api
  File "/root/PycharmProjects/DLS/app/backend/api.py", line 7, in <module>
    from app.backend.dataset.api import dataset
  File "/root/PycharmProjects/DLS/app/backend/dataset/api.py", line 18, in <module>
    datasetWatcher.refreshDatasetsInfo()
  File "/root/PycharmProjects/DLS/app/backend/core/datasets/dbwatcher.py", line 32, in refreshDatasetsInfo
    raise Exception('Cant find directory with datasets [%s]' % self.dirDatasets)
Exception: Cant find directory with datasets [/root/PycharmProjects/DLS/dataset-import-test/../data/datasets]

**Comment by gakarak** [comment]
Hi, Odin
You can try DLS snapshot from AI-Hackhathon-2016 (include dataset, network templates and pretrainde model):
https://yadi.sk/d/fbtMjOAY3NtKMD
